export const LEVELS = {
 levels: ["المرحلة الابتدائية", "المرحلة الاعدادية", "المرحلة الثانوية"],
 primary: [
  "الصف الاول",
  "الصف الثاني",
  "الصف الثالث",
  "الصف الرابع",
  "الصف الخامس",
  "الصف السادس",
 ],
 middle: ["الصف الاول", "الصف الثاني", "الصف الثالث"],
 high: ["الصف الاول", "الصف الثاني", "الصف الثالث"],
};

export const FakeGroups = [
 {
  id: 1,
  name: "المجموعة الاولى",
  students: [
   {
    id: 1,
    name: "محمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الاولى",
    status: "active",
   },
   {
    id: 2,
    name: "احمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الاولى",
    status: "active",
   },
   {
    id: 3,
    name: "علي",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الاولى",
    status: "active",
   },
   {
    id: 4,
    name: "محمود",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الاولى",
    status: "active",
   },
   {
    id: 5,
    name: "احمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الاولى",
    status: "active",
   },
  ],
 },
 {
  id: 2,
  name: "المجموعة الثانية",
  students: [
   {
    id: 1,
    name: "محمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثانية",
    status: "active",
   },
   {
    id: 2,
    name: "احمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثانية",
    status: "active",
   },
   {
    id: 3,
    name: "علي",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثانية",
    status: "active",
   },
   {
    id: 4,
    name: "محمود",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثانية",
    status: "active",
   },
   {
    id: 5,
    name: "احمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثانية",
    status: "active",
   },
  ],
 },
 {
  id: 3,
  name: "المجموعة الثالثة",
  students: [
   {
    id: 1,
    name: "محمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثالثة",
    status: "active",
   },
   {
    id: 2,
    name: "احمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثالثة",
    status: "active",
   },
   {
    id: 3,
    name: "علي",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثالثة",
    status: "active",
   },
   {
    id: 4,
    name: "محمود",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثالثة",
    status: "active",
   },
   {
    id: 5,
    name: "احمد",
    phone: "01000000000",
    email: "",
    level: "الصف الاول",
    subLevel: 0,
    group: "المجموعة الثالثة",
    status: "active",
   },
  ],
 },
];

export const constraints = {
 primary: {
  text: "المرحلة الابتدائية",
  content: [
   "الصف الاول",
   "الصف الثاني",
   "الصف الثالث",
   "الصف الرابع",
   "الصف الخامس",
   "الصف السادس",
  ],
 },
 middle: {
  text: "المرحلة الاعدادية",
  content: ["الصف الاول", "الصف الثاني", "الصف الثالث"],
 },
 high: {
  text: "المرحلة الثانوية",
  content: ["الصف الاول", "الصف الثاني", "الصف الثالث"],
 },
};
